/*
 * Created on 20 oct. 2014 ( Time 21:44:44 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.test.persistence;


import emn.tp.bean.jpa.ParticipantEntity;
import emn.tp.mock.ParticipantEntityMock;
import emn.tp.persistence.PersistenceServiceProvider;
import emn.tp.persistence.services.ParticipantPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Participant persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParticipantPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ParticipantPersistence service = PersistenceServiceProvider.getService(ParticipantPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Participant persistence : delete + load ..." );
		
		ParticipantPersistence service = PersistenceServiceProvider.getService(ParticipantPersistence.class);
		
		ParticipantEntityMock mock = new ParticipantEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(ParticipantPersistence service, ParticipantEntityMock mock, String mail ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ParticipantEntity entity = service.load( mail );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( mail ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Events
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( mail );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
