
/*
 * Created on 21 oct. 2014 ( Time 08:51:15 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.mock;

import java.util.LinkedList;
import java.util.List;

import emn.tp.bean.jpa.ParticipantEntity;
import emn.tp.mock.tool.MockValues;

public class ParticipantEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ParticipantEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(30) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ParticipantEntity createInstance( String mail ) {
		ParticipantEntity entity = new ParticipantEntity();
		// Init Primary Key fields
		entity.setMail( mail) ;
		// Init Data fields
		entity.setName( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setFirstname( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setCompany( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ParticipantEntity> createList(int count) {
		List<ParticipantEntity> list = new LinkedList<ParticipantEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
