
/*
 * Created on 28 oct. 2014 ( Time 14:00:21 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.mock;

import java.util.LinkedList;
import java.util.List;

import emn.tp.bean.jpa.ParticipateEntity;
import emn.tp.mock.tool.MockValues;

public class ParticipateEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ParticipateEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ParticipateEntity createInstance( Integer participantid, Integer eventid ) {
		ParticipateEntity entity = new ParticipateEntity();
		// Init Primary Key fields
		entity.setParticipantid( participantid) ;
		entity.setEventid( eventid) ;
		// Init Data fields
		// Init Link fields (if any)
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ParticipateEntity> createList(int count) {
		List<ParticipateEntity> list = new LinkedList<ParticipateEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
