
/*
 * Created on 20 oct. 2014 ( Time 21:44:44 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.mock;

import java.util.LinkedList;
import java.util.List;

import emn.tp.bean.jpa.UsersEntity;
import emn.tp.mock.tool.MockValues;

public class UsersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UsersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(30) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UsersEntity createInstance( String mail ) {
		UsersEntity entity = new UsersEntity();
		// Init Primary Key fields
		entity.setMail( mail) ;
		// Init Data fields
		entity.setName( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UsersEntity> createList(int count) {
		List<UsersEntity> list = new LinkedList<UsersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
