/*
 * Created on 20 oct. 2014 ( Time 21:44:44 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.persistence.services;

import java.util.List;
import java.util.Map;

import emn.tp.bean.jpa.ParticipantEntity;

/**
 * Basic persistence operations for entity "Participant"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface ParticipantPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param participant
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(ParticipantEntity participant) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param mail
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String mail) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param participant
	 */
	public void insert(ParticipantEntity participant) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param mail
	 * @return the entity loaded (or null if not found)
	 */
	public ParticipantEntity load(String mail) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<ParticipantEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<ParticipantEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<ParticipantEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param participant
	 * @return
	 */
	public ParticipantEntity save(ParticipantEntity participant) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<ParticipantEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
