/*
 * Created on 20 oct. 2014 ( Time 21:44:42 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package emn.tp.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "EVENTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EVENTS", schema="APP" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EventsEntity.countAll", query="SELECT COUNT(x) FROM EventsEntity x" )
} )
public class EventsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="URL", nullable=false, length=30)
    private String     url          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="EVENTID", nullable=false)
    private Integer    eventid      ;

    @Column(name="NAME", nullable=false, length=30)
    private String     name         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STARTDATE", nullable=false)
    private Date       startdate    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDDATE", nullable=false)
    private Date       enddate      ;

    @Column(name="ADDRESS", nullable=false, length=30)
    private String     address      ;

    @Column(name="PUBLISHED", nullable=false)
    private Short      published    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="events", targetEntity=ParticipantEntity.class)
    private List<ParticipantEntity> listOfParticipant;

    @OneToMany(mappedBy="events", targetEntity=UsersEntity.class)
    private List<UsersEntity> listOfUsers ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUrl( String url ) {
        this.url = url ;
    }
    public String getUrl() {
        return this.url;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : EVENTID ( INTEGER ) 
    public void setEventid( Integer eventid ) {
        this.eventid = eventid;
    }
    public Integer getEventid() {
        return this.eventid;
    }

    //--- DATABASE MAPPING : NAME ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : STARTDATE ( TIMESTAMP ) 
    public void setStartdate( Date startdate ) {
        this.startdate = startdate;
    }
    public Date getStartdate() {
        return this.startdate;
    }

    //--- DATABASE MAPPING : ENDDATE ( TIMESTAMP ) 
    public void setEnddate( Date enddate ) {
        this.enddate = enddate;
    }
    public Date getEnddate() {
        return this.enddate;
    }

    //--- DATABASE MAPPING : ADDRESS ( VARCHAR ) 
    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    //--- DATABASE MAPPING : PUBLISHED ( SMALLINT ) 
    public void setPublished( Short published ) {
        this.published = published;
    }
    public Short getPublished() {
        return this.published;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfParticipant( List<ParticipantEntity> listOfParticipant ) {
        this.listOfParticipant = listOfParticipant;
    }
    public List<ParticipantEntity> getListOfParticipant() {
        return this.listOfParticipant;
    }

    public void setListOfUsers( List<UsersEntity> listOfUsers ) {
        this.listOfUsers = listOfUsers;
    }
    public List<UsersEntity> getListOfUsers() {
        return this.listOfUsers;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(url);
        sb.append("]:"); 
        sb.append(eventid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(startdate);
        sb.append("|");
        sb.append(enddate);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(published);
        return sb.toString(); 
    } 

}
