/*
 * Created on 28 oct. 2014 ( Time 14:55:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package emn.tp.bean.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ParticipateEntity" ( stored in table "PARTICIPATE" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ParticipateEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="PARTICIPANTID", nullable=false)
    private Integer    participantid ;
    
    @Column(name="EVENTID", nullable=false)
    private Integer    eventid      ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ParticipateEntityKey() {
        super();
    }

    public ParticipateEntityKey( Integer participantid, Integer eventid ) {
        super();
        this.participantid = participantid ;
        this.eventid = eventid ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setParticipantid( Integer value ) {
        this.participantid = value;
    }
    public Integer getParticipantid() {
        return this.participantid;
    }

    public void setEventid( Integer value ) {
        this.eventid = value;
    }
    public Integer getEventid() {
        return this.eventid;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ParticipateEntityKey other = (ParticipateEntityKey) obj; 
		//--- Attribute participantid
		if ( participantid == null ) { 
			if ( other.participantid != null ) 
				return false ; 
		} else if ( ! participantid.equals(other.participantid) ) 
			return false ; 
		//--- Attribute eventid
		if ( eventid == null ) { 
			if ( other.eventid != null ) 
				return false ; 
		} else if ( ! eventid.equals(other.eventid) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute participantid
		result = prime * result + ((participantid == null) ? 0 : participantid.hashCode() ) ; 
		//--- Attribute eventid
		result = prime * result + ((eventid == null) ? 0 : eventid.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(participantid); 
		sb.append("|"); 
		sb.append(eventid); 
        return sb.toString();
    }
}
