/*
 * Created on 28 oct. 2014 ( Time 14:55:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package emn.tp.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import emn.tp.bean.jpa.ParticipateEntity;
import emn.tp.bean.jpa.ParticipateEntityKey;
import emn.tp.persistence.commons.jpa.GenericJpaService;
import emn.tp.persistence.commons.jpa.JpaOperation;
import emn.tp.persistence.services.ParticipatePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Participate" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParticipatePersistenceJPA extends GenericJpaService<ParticipateEntity, ParticipateEntityKey> implements ParticipatePersistence {

	/**
	 * Constructor
	 */
	public ParticipatePersistenceJPA() {
		super(ParticipateEntity.class);
	}

	@Override
	public ParticipateEntity load( Integer participantid, Integer eventid ) {
		// Build the composite key
		ParticipateEntityKey key = new ParticipateEntityKey( participantid, eventid );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer participantid, Integer eventid ) {
		// Build the composite key
		ParticipateEntityKey key = new ParticipateEntityKey( participantid, eventid );
		return super.delete( key );
	}

	@Override
	public boolean delete(ParticipateEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			ParticipateEntityKey key = new ParticipateEntityKey( entity.getParticipantid(), entity.getEventid() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ParticipateEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
